version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: sryzen
    ports:
      - "5432:5432"
